# Site settings
title: Brian Nadon
general_email: brian.nadon@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Bioinformatics scientist and part-time music/audio enthusiast.

baseurl: "/" # the subpath of your site, e.g. /blog/

url: "https://briannadon.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: briannadon
linkedin_username: brian-nadon
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title